### GET /
GET http://localhost:3000/

### GET /studios 
GET http://localhost:3000/studios

### GET /studios/<studio-id>
GET http://localhost:3000/studios/studio-0


### GET /studios/<studio-id>/classes
GET http://localhost:3000/studios/studio-1/classes

### POST /studios
POST http://localhost:3000/studios
Content-Type: application/json

{
  "ownerId": "owner-0",
  "name": "Another Dance Co.",
  "address": {
    "addr1": "58 Delancey St."
  }
}